ARG NODE_VERSION=22.16.0

FROM node:${NODE_VERSION}-alpine

ARG PNPM_VERSION=10.30.3
ARG PORT=5000

# Installing PNPM 
RUN --mount=type=cache,target=/root/.npm \
    npm install -g pnpm@${PNPM_VERSION}

WORKDIR /usr/src/app

# Run application as a non-root user.
USER node

# Expose the port that the application listens on.
EXPOSE ${PORT}